version: '3'

services:
  dashboard_api:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: dashboard_api
    # command: python manage.py runserver 0.0.0.0:8000
    command: ./wait-for-it.sh pg_db:5432 -- ./docker-entrypoint.sh
    restart: on-failure
    volumes:
      - .:/app
      - ./filtered_occurrences.csv:/tmp/filtered.csv
    ports:
      - "8000:8000"
    networks:
      - inhs-api
    depends_on:
      - pg_db

  pg_db:
    image: kartoza/postgis:latest
    restart: always
    container_name: pg_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./filtered_occurrences.csv:/tmp/filtered.csv
      - ./filtered_occurrences.csv:/docker-entrypoint-initdb.d/filtered.csv
      # - ./import_data.sql:/docker-entrypoint-initdb.d/import_data.sql
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - inhs-api

networks:
  inhs-api:
    driver: bridge

volumes:
  postgres_data:
