# Generated by Django 5.1.4 on 2025-01-03 19:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GISFeature',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kingdom', models.CharField(max_length=255)),
                ('phylum', models.CharField(max_length=255)),
                ('phylum_class', models.CharField(choices=[('Amphibia', 'Amphibia'), ('Reptilia', 'Reptilia')], default='Amphibia', max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('genus', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255)),
                ('decimal_latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('decimal_longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
