# Generated by Django 5.1.4 on 2025-01-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inhs_herp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gisfeature',
            table='gisfeatures',
        ),
    ]
